### ISSUE TITLE
The download link of object proposals or object detections is down?

### ISSUE THREAD

**Issue by yichunk** [lichengunc/visdif_emb_guide2_reinforce#1]
Is the download link of object proposals or object detections down? I cannot access to it.
http://tlberg.cs.unc.edu/licheng/referit/data/detections.zip

Could you please check it out? Thanks!

**Comment by lichengunc** [comment]
Yes, please go use bvisionweb1.cs.unc.edu/licheng/referit/data/detections.zip

**Comment by lichengunc** [comment]
Updated. Thanks for remind!
