### ISSUE TITLE
Error Downloading the pretrained model

### ISSUE THREAD

**Issue by vanpersie32** [lichengunc/visdif_emb_guide2_reinforce#2]
When I try to download the pretrained model from link [http://tlberg.cs.unc.edu/licheng/referit/visdif_emb_guide2_reinforce/models/refcoco_unc.zip](http://tlberg.cs.unc.edu/licheng/referit/visdif_emb_guide2_reinforce/models/refcoco_unc.zip) I fail to connect to the website

**Comment by srama2512** [comment]
Try accessing them here: http://bvisionweb1.cs.unc.edu/licheng/referit/visdif_emb_guide2_reinforce/models/refcoco_unc.zip

**Comment by vanpersie32** [comment]
thanks

**Comment by lichengunc** [comment]
Updated, thanks for remind!
