### ISSUE TITLE
How does the Mine hard affect the performance?

### ISSUE THREAD

**Issue by ghost** [lichengunc/visdif_emb_guide2_reinforce#3]
Hi,
Great repo!
How does the Min hard affect the performance?

**Comment by lichengunc** [comment]
I remember I tried online hard negative mining and offline hard negative mining. The later helps improving the comprehension performance. I think it's worthwhile to try using hard mining. :-)

**Comment by ghost** [comment]
Thanks for the rely!
The negative samples are only from the same images? Or from the entire training set based on the cossin similarity? How did you calculate the cos similarity? based on the concatenated feature or solely the annotation's feature?

**Comment by lichengunc** [comment]
Oh, when I mean the hard negative it is not just sampling same-type object from the same image. Actually after each-epoch training, I picked the most confusing object for each expression and use them as hard mined ones. It will boost the performance. :-)

**Comment by ghost** [comment]
Aha, thanks! Extremely helpful! ;)
I noticed that you used FC8 layer of VGG as the initialization of the FC layers in Visual encoder. Have you tried initializing those FC layers randomly (e.g. Xavier/MSRA init)? Will it harm the performances a lot?

**Comment by lichengunc** [comment]
I don't think so. :-) The results should be quite similar as far as I remember.
The reason I used FC8 is for fair comparison with "Generation and Comprehension of Unambiguous Object Descriptions" at that time.
